language: java
dist: trusty

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9

script:
  - mvn clean install jacoco:report coveralls:report
  - mvn -f math-plugin/pom.xml clean package jacoco:report
  - mvn -f string-plugin/pom.xml clean package jacoco:report
  - mvn -f lodash-plugin/pom.xml clean package jacoco:report
  - mvn -f examples/pom.xml clean package

addons:
   hosts:
       - travis
   hostname: travis

before_script:
  - pip install --user codecov

after_success:
  - codecov
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
