language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - mvn clean install jacoco:report coveralls:jacoco
  - mvn -f math-plugin/pom.xml clean package jacoco:report
  - mvn -f string-plugin/pom.xml clean package jacoco:report
  - mvn -f lodash-plugin/pom.xml clean package jacoco:report
  - mvn -f examples/pom.xml clean package

addons:
   hosts:
       - travis
   hostname: travis

before_script:
  - pip install --user codecov

after_success:
  - codecov
